select * from actor;
SELECT first_name, last_name, address_id FROM Customer WHERE store_id = '2';
SELECT * FROM customer;
SELECT * FROM customer LIMIT 5;
SELECT first_name, last_name FROM customer LIMIT 5;
SELECT COUNT(*) as Total_Rec FROM customer;
SELECT * FROM customer WHERE store_id = '2';
SELECT * FROM customer WHERE address_id > '3' AND address_id < 25;
SELECT * FROM customer WHERE address_id BETWEEN '3' AND 25;
SELECT * FROM customer WHERE address_id >= '25' AND store_id = 2;
SELECT * FROM customer WHERE address_id not in (25,2,5);
SELECT first_name as FN, last_name as LN FROM customer LIMIT 5;
SELECT max(length) as maximum_length, min(length) as minimum_length, sum(length) as sum_length from film where rating='G';
SELECT rating, max(length) as maximum_length, min(length) as minimum_length, sum(length) as sum_length from film group by rating;
SELECT rating, max(length) as maximum_length, min(length) as minimum_length, sum(length) as sum_length from film group by rating order by rating desc;
SELECT rating, count(*) as rw_count, max(length) as maximum_length, min(length) as minimum_length, sum(length) as sum_length from film group by rating order by rating desc, rw_count desc;
SELECT rating, count(*) as rw_count, max(length) as maximum_length, min(length) as minimum_length, sum(length) as sum_length from film group by rating order by rating desc, rw_count desc having count(*) > 200;
SELECT customer_id, sum(amount) as spend from payment group by customer_id having sum(amount) order by 2 desc;
SELECT * FROM address limit 5;
SELECT concat(address," , ",district," , ", city_id," ,POSTAL CODE ", postal_code) as full_address FROM address limit 5;
SELECT * FROM customer LIMIT 5;
SELECT * FROM address LIMIT 5;
SELECT a.customer_id, a.first_name, a.last_name, b.district FROM customer as a LEFT JOIN address as b on a.address_id = b.address_id LIMIT 5;
SELECT a.customer_id, a.first_name, a.last_name, b.district, b.postal_code FROM customer as a inner JOIN address as b on a.address_id = b.address_id LIMIT 5;
SELECT a.customer_id, a.first_name, a.last_name, b.district, b.postal_code FROM customer as a outer JOIN address as b on a.address_id = b.address_id LIMIT 5;
SELECT rating FROM film;
SELECT distinct rating FROM film;
#lab
SELECT * FROM actor WHERE first_name="SCARLETT";
SELECT concat(first_name," ",last_name) as full_name FROM actor WHERE first_name="SCARLETT" order by last_name;
SELECT max(amount)  as max_payment FROM payment;
SELECT count(max_payment) ,max(amount)  as max_payment FROM payment group by max_payment;
SELECT count(last_name) from actor;
SELECT count(distinct last_name) from actor;
SELECT count(distinct country) from country;
SELECT name from language order by name;
SELECT customer_id, sum(amount) as total_spend, avg(amount) as average_spend from payment group by customer_id order by total_spend desc limit 5;
SELECT * from film LIMIT 5;
SELECT * from film_actor LIMIT 5;
SELECT * from actor LIMIT 5;
SELECT * from actor where first_name='RIP' and last_name='crawford';
SELECT  b.first_name, b.last_name, c.title as moive, c.description from film_actor as a join actor as b on a.actor_id = b.actor_id join film as c on a.film_id = c.film_id WHERE b.first_name='RIP' and b.last_name='crawford';